### ISSUE TITLE
非推奨となっているREST APIについて

### ISSUE THREAD

**Issue by mizuka123** [MtkN1/pybybit#3]
一部REST APIが非推奨となっていますが、v2対応を行われる予定はありますでしょうか。
![2021-02-06_22h13_37](https://user-images.githubusercontent.com/5837315/107119076-922b6f00-68c8-11eb-9aa9-d4fad26d1083.png)

**Comment by MtkN1** [comment]
正直なところサボっていましたが、BybitのREST APIは更新頻度は多く機械的に解決できる方法がなかったのが現状です。

しかし放置したままでは問題ですし、折角イシューを上げてくださったので数日以内に対応したいと思います。

補足、今回のように未対応のREST APIに関してはプライベートメソッド`_request`で呼ぶことが可能です。
```
bybit = pybybit.API('api_key', 'api_secret')
r = bybit.rest._request('POST', '/v2/private/...', {'symbol': ...}, private=True)
```

**Comment by MtkN1** [comment]
対応完了
- ✅ エンドポイント更新
- ✅自動生成スクリプト作成
- ✅Wikiにエンドポイント更新表追加
