### ISSUE TITLE
tp_trigger_byとsl_trigger_by

### ISSUE THREAD

**Issue by tatsuiman** [MtkN1/pybybit#7]
tp_trigger_byとsl_trigger_byの追加をお願いできないでしょうか？

https://github.com/MtkN1/pybybit/blob/master/pybybit/rest.py#L304

[bybit api 仕様](https://bybit-exchange.github.io/docs/inverse/#t-placeactive)

**Comment by MtkN1** [comment]
イシュー報告ありがとうございます。エンドポイントを最新の内容に更新しました。
クローズさせて頂きます。
